config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #root 'rooms#index'
  root 'welcome#index'

  resources :rooms, only:[:index, :show] do
    resources :seats, only: [:index, :show]
  end

  resources :logs, only:[:index, :show]

  resources :tasks do
    collection do
      get 'checkin'
    end
  end

  mount API::Test => '/api'
  mount API::Library => '/api'

  get 'update_crontab', to: 'crontab#update_crontab_file'
  get 'deploy_method', to: 'deploy#index'

  mount Sidekiq::Web => '/sidekiq'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/log.rb
class Log < ApplicationRecord
  paginates_per 10

  def status
    return eval(self.data)['status']
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :seats
end

app/models/seat.rb
class Seat < ApplicationRecord
  belongs_to :room
end

app/models/task.rb
class Task < ApplicationRecord
  validates :username, presence: true
  validates :password, presence: true
  validates :start, presence: true
  validates :end, presence: true
  validates :seat, presence: true

  def token
    page = Mechanize.new
    page.get "http://seat.ujn.edu.cn/rest/auth?username=#{self.username}&password=#{self.password}"

    JSON.parse(page.page.body)['data']['token']
  end
end

app/models/text.rb
class Text < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/crontab_controller.rb
class CrontabController < ApplicationController
  def update_crontab_file
    CrontabFileUpdateJob.perform_later
    redirect_to :controller => 'tasks', :action => 'index'
  end
end

app/controllers/deploy_controller.rb
class DeployController < ApplicationController
  def index

  end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  def index
    @logs = Log.order(id: :desc).page params[:page]
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all.order("campus ASC").order("floor ASC")
  end

  def new
    @room = Romm.new
  end

  def show
    @room = Room.find(params[:id])
    @seats = @room.seats.order("seat_id ASC")
  end

  def create
    @room = Room.new(room_params)
    @room.save
    redirect_to rooms_path
  end

private
  def room_params
    params.require(:room).permit(:id, :name, :campus, :floor)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path, notice: "Update Success"
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    flash[:alert] = "Task deleted"
    redirect_to tasks_path
  end

  def create
    @task = Task.new(task_params)
    @task.save if Seat.find(task_params[:seat])

    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def checkin
    @available = []; @token = []
    @tasks = Task.all; @hour = Time.new.hour
    @range = @hour * 60..(@hour + 1) * 60

    @tasks.each do |task|
      @available << task if @range === task.start.to_i
    end

    @available.each do |task|
      @token << task.token
    end

    render :json => @token, :callback => params[:callback]
  end

  private
  def task_params
    params.require(:task).permit(:username, :password, :start, :end, :seat, :remark)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crontab_helper.rb
module CrontabHelper
end

app/helpers/deploy_helper.rb
module DeployHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze
  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end
  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning"
  end
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/logs/_table.html.erb
<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th>ID</th>
      <th>USERNAME</th>
      <th>SEAT</th>
      <th>STATUS</th>
      <th>START</th>
      <th>END</th>
      <th>CREATED</th>
    </tr>
  </thead>

  <tbody>
    <% @logs.each do |log| %>
      <% if log.status == 'success' %>
        <tr class="success">
          <td><%= log.id %></td>
          <td><%=log.username%></td>
          <td><%=log.seat%></td>
          <td><%=log.status%></td>
          <td><%=log.start_time%></td>
          <td><%=log.end_time %></td>
          <td><%=log.created_at %></td>
        </tr>
      <% else %>
        <tr class="danger">
          <td><%= log.id %></td>
          <td><%=log.username%></td>
          <td><%=log.seat%></td>
          <td><%=log.status%></td>
          <td><%=log.start_time%></td>
          <td><%=log.end_time %></td>
          <td><%=log.created_at %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<%= paginate @logs, :theme => 'twitter-bootstrap-3' %></div>

app/views/logs/index.html.erb
<div class="container">
  <div class="jumbotron">
    <h1>Log page</h1>
    <p>Log pages are used to store performance and error data.</p>
    <p><a class="btn btn-primary btn-lg">Learn more</a></p>
  </div>
  <br />
  <%= render 'table' %>
</div>

app/views/rooms/index.html.erb
<div class="container">
  <table class="table table-hover">
    <thead>
      <tr>
        <td>#</td>
        <td>ID</td>
        <td>NAME</td>
        <td>FLOOR</td>
        <td>SEATS</td>
        <td>CAMPUS</td>
      </tr>
    </thead>
    <tbody>
      <% @rooms.each do |room| %>
        <tr>
          <td>#</td>
          <td><%= link_to(room.id, room_path(room)) %></td>
          <td><%= room.name %></td>
          <td><%= room.floor %></td>
          <td><%= room.seat_counts %></td>
          <td><%= room.campus %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/rooms/show.html.erb
<div class="col-md-12">
  <h2><%= @room.name %></h2>
  <table class="table table-hover">
    <thead>
      <tr>
        <td>#</td>
        <td>ID</td>
        <td>SEAT_ID</td>
        <td>SEAT_NAME</td>
      </tr>
    </thead>
    <tbody>
      <% @seats.each do |seat| %>
        <tr>
          <td>#</td>
          <td><%= link_to seat.id, new_task_path(:seat_id => seat.id) %></td>
          <td><%= seat.seat_id %></td>
          <td><%= seat.seat_name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/tasks/_form.html.erb
<%= form_for @task do |f| %>
<div class="form-group">
    <div class="form-group string optional">
        <%= f.label "username", :class => "string optional control-label" %>
        <%= f.text_field :username, :class => "string optional form-control form-control" %>
    </div>
    <div class="form-group string optional">
        <%= f.label "password", :class => "string optional control-label" %>
        <%= f.text_area :password, :class => "string optional form-control" %>
    </div>
    <div class="form-group string optional">
        <%= f.label "start", :class => "string optional control-label" %>
        <%= f.text_area :start, :class => "string optional form-control" %>
    </div>
    <div class="form-group string optional">
        <%= f.label "end", :class => "string optional control-label" %>
        <%= f.text_area :end, :class => "string optional form-control" %>
    </div>
    <div class="form-group string optional">
        <% if params[:seat_id] == nil %>
          <%= f.label "seat", :class => "string optional control-label" %>
          <%= f.text_area :seat, :class => "string optional form-control" %>
        <% end %>
        <% if params[:seat_id] != nil %>
          <%= f.label "seat", :class => "string optional control-label" %>
          <%= f.text_area :seat, :value => params[:seat_id],:class => "string optional form-control" %>
        <% end %>
    </div>
    <div class="form-group string optional">
        <%= f.label "remark", :class => "string optional control-label" %>
        <%= f.text_area :remark, :class => "string optional form-control" %>
    </div>
</div>
<%= f.submit "Submit", class: "btn btn-primary", data: { disable_with: "Submitting..." } %>
<% end %>

app/views/tasks/edit.html.erb
<div class="col-md-4 col-md-offset-4">
    <h2>Edit a new task</h2>
    <hr>
    <%= render "form" %>
</div>

app/views/tasks/index.html.erb
<div class="container">
  <div class="task">
    <%= link_to("New task", new_task_path, class: "btn btn-primary") %>
    <%= link_to("Update Crontab File", update_crontab_path, class: "btn btn-primary") %>
  </div>
  <br />
  <table class="table table-hover table-striped">
    <thead>
      <tr>
        <td>#</td>
        <td>ID</td>
        <td>USERNAME</td>
        <td>START</td>
        <td>END</td>
        <td>SEAT</td>
        <td>REMARK</td>
      </tr>
    </thead>
    <tbody>
      <% @tasks.each do |task| %>
        <% seat = Seat.find_by(id: task.seat) %>
        <% if seat != nil %>
          <tr>
            <td>#</td>
            <td><%= task.id %></td>
            <td><%= task.username %></td>
            <td><%= (task.start.to_i)/60 %> o'clock</td>
            <td><%= (task.end.to_i)/60 %> o'clock</td>
            <td><%= seat.seat_name %></td>
            <td><%= task.remark %></td>
            <td>
              <%= link_to("Edit", edit_task_path(task), class: "btn btn-xs btn-info")%>
              <%= link_to("Delete", task_path(task),    class: "btn btn-xs btn-danger",
                          method: :delete, data: { confirm: "Are you sure?" } )%>
            </td>
          </tr>
        <% else %>
          <tr class="warning">
            <td>#</td>
            <td><%= task.id %></td>
            <td><%= task.username %></td>
            <td><%= (task.start.to_i)/60 %> o'clock</td>
            <td><%= (task.end.to_i)/60 %> o'clock</td>
            <td>This seat don't exist</td>
            <td><%= task.remark %></td>
            <td>
              <%= link_to("Edit", edit_task_path(task), class: "btn btn-xs btn-info")%>
              <%= link_to("Delete", task_path(task),    class: "btn btn-xs btn-danger",
                          method: :delete, data: { confirm: "Are you sure?" } )%>
            </td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/tasks/new.html.erb
<div class="col-md-4 col-md-offset-4">
    <h2>Create a new task</h2>
    <hr>
    <%= render "form" %>
</div>

app/views/welcome/index.html.erb
<div class="container">
  <div class="jumbotron">
    <h1>Booking-Daddy</h1>
    <p>
      懒觉助手 考研克星 嘻嘻嘻嘻嘻嘻
    </p>
    <p>
      <a class="btn btn-lg btn-primary" href="https://github.com/syhsyh9696/library-seats-api">Project here</a>
    </p>
  </div>
</div>