config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #root 'rooms#index'
  root 'welcome#index'

  resources :rooms, only:[:index, :show] do
    resources :seats, only: [:index, :show]
  end

  resources :logs, only:[:index, :show]

  resources :tasks do
    collection do
      get 'checkin'
    end
  end

  mount API::Test => '/api'
  mount API::Library => '/api'

  get 'update_crontab', to: 'crontab#update_crontab_file'
  get 'deploy_method', to: 'deploy#index'

  mount Sidekiq::Web => '/sidekiq'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/log.rb
class Log < ApplicationRecord
  paginates_per 10

  def status
    return eval(self.data)['status']
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :seats
end

app/models/seat.rb
class Seat < ApplicationRecord
  belongs_to :room
end

app/models/task.rb
class Task < ApplicationRecord
  validates :username, presence: true
  validates :password, presence: true
  validates :start, presence: true
  validates :end, presence: true
  validates :seat, presence: true

  def token
    page = Mechanize.new
    page.get "http://seat.ujn.edu.cn/rest/auth?username=#{self.username}&password=#{self.password}"

    JSON.parse(page.page.body)['data']['token']
  end
end

app/models/text.rb
class Text < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/crontab_controller.rb
class CrontabController < ApplicationController
  def update_crontab_file
    CrontabFileUpdateJob.perform_later
    redirect_to :controller => 'tasks', :action => 'index'
  end
end

app/controllers/deploy_controller.rb
class DeployController < ApplicationController
  def index

  end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  def index
    @logs = Log.order(id: :desc).page params[:page]
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all.order("campus ASC").order("floor ASC")
  end

  def new
    @room = Romm.new
  end

  def show
    @room = Room.find(params[:id])
    @seats = @room.seats.order("seat_id ASC")
  end

  def create
    @room = Room.new(room_params)
    @room.save
    redirect_to rooms_path
  end

private
  def room_params
    params.require(:room).permit(:id, :name, :campus, :floor)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path, notice: "Update Success"
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    flash[:alert] = "Task deleted"
    redirect_to tasks_path
  end

  def create
    @task = Task.new(task_params)
    @task.save if Seat.find(task_params[:seat])

    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def checkin
    @available = []; @token = []
    @tasks = Task.all; @hour = Time.new.hour
    @range = @hour * 60..(@hour + 1) * 60

    @tasks.each do |task|
      @available << task if @range === task.start.to_i
    end

    @available.each do |task|
      @token << task.token
    end

    render :json => @token, :callback => params[:callback]
  end

  private
  def task_params
    params.require(:task).permit(:username, :password, :start, :end, :seat, :remark)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crontab_helper.rb
module CrontabHelper
end

app/helpers/deploy_helper.rb
module DeployHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze
  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end
  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning"
  end
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
    <p class="text-center">Copyright ©2017 syhsyh9696
        <br>Design by
        <a href="https://github.com/syhsyh9696" target=_new>syhsyh9696</a>
    </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="nnavbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="/">BOOKING-DADDY</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active">
                  <%= link_to("Rooms", rooms_path) %>
                </li>
                <li>
                  <%= link_to("Tasks", tasks_path) %>
                </li>
                <li>
                  <%= link_to("Logs", logs_path)%>
                </li>
            </ul>
          <%= render 'common/signed' %>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>BOOKING-DADDY</title>
        <%= csrf_meta_tags %>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>
    <body>
        <div class="container-fluid">
            <%= render "common/navbar" %>
            <%= render "common/flashes" %>
            <%= yield %>
        </div>
        <%= render "common/footer" %>
    </body>
</html>